from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_DIR = ROOT / "requirements" / "locks"
CPU_LOCK = LOCK_DIR / "cpu-dev.lock.txt"
ROCM_LOCK = LOCK_DIR / "rocm-train.lock.txt"


def _run(cmd: list[str]) -> None:
	res = subprocess.run(cmd, cwd=ROOT)
	if res.returncode != 0:
		raise SystemExit(res.returncode)


def _normalized_lock_text(path: Path) -> str:
	lines = path.read_text(encoding="utf-8").splitlines()
	filtered: list[str] = []
	for line in lines:
		if line.startswith("# This file was autogenerated by uv via the following command:"):
			continue
		if line.startswith("#    uv export "):
			continue
		filtered.append(line)
	return "\n".join(filtered).strip() + "\n"


def _generate(python_version: str) -> None:
	LOCK_DIR.mkdir(parents=True, exist_ok=True)
	_run(["uv", "lock", "--python", python_version])
	_run(
		[
			"uv",
			"export",
			"--locked",
			"--python",
			python_version,
			"--format",
			"requirements.txt",
			"--no-default-groups",
			"--only-group",
			"cpu_dev",
			"-o",
			str(CPU_LOCK.relative_to(ROOT)),
		]
	)
	_run(
		[
			"uv",
			"export",
			"--locked",
			"--python",
			python_version,
			"--format",
			"requirements.txt",
			"--no-default-groups",
			"--only-group",
			"rocm_train",
			"-o",
			str(ROCM_LOCK.relative_to(ROOT)),
		]
	)


def _check(python_version: str) -> None:
	_run(["uv", "lock", "--check", "--python", python_version])
	if not CPU_LOCK.exists() or not ROCM_LOCK.exists():
		raise SystemExit("Missing exported lockfiles. Run: python scripts/lock_profiles.py generate")

	# Re-export to temp and compare byte-for-byte.
	tmp_cpu = LOCK_DIR / ".cpu-dev.lock.tmp.txt"
	tmp_rocm = LOCK_DIR / ".rocm-train.lock.tmp.txt"
	try:
		_run(
			[
				"uv",
				"export",
				"--locked",
				"--python",
				python_version,
				"--format",
				"requirements.txt",
				"--no-default-groups",
				"--only-group",
				"cpu_dev",
				"-o",
				str(tmp_cpu.relative_to(ROOT)),
			]
		)
		_run(
			[
				"uv",
				"export",
				"--locked",
				"--python",
				python_version,
				"--format",
				"requirements.txt",
				"--no-default-groups",
				"--only-group",
				"rocm_train",
				"-o",
				str(tmp_rocm.relative_to(ROOT)),
			]
		)
		if _normalized_lock_text(tmp_cpu) != _normalized_lock_text(CPU_LOCK):
			raise SystemExit("cpu-dev.lock.txt is stale. Run: python scripts/lock_profiles.py generate")
		if _normalized_lock_text(tmp_rocm) != _normalized_lock_text(ROCM_LOCK):
			raise SystemExit("rocm-train.lock.txt is stale. Run: python scripts/lock_profiles.py generate")
	finally:
		if tmp_cpu.exists():
			tmp_cpu.unlink()
		if tmp_rocm.exists():
			tmp_rocm.unlink()


def main() -> int:
	parser = argparse.ArgumentParser(description="Generate/check backend uv lock artifacts")
	parser.add_argument("mode", choices=["generate", "check"])
	parser.add_argument("--python", default="3.11.14", dest="python_version")
	args = parser.parse_args()

	if args.mode == "generate":
		_generate(args.python_version)
		return 0
	_check(args.python_version)
	return 0


if __name__ == "__main__":
	sys.exit(main())
